// Tower.client/src/components/EventForm.vue
<template>
    <div class="row flex-column">

        <form @submit.prevent="createEvent" id="event-form">
            <div class="col">
                <label class="text-dark m-2">Event Name: </label>
                <input v-model="editable.name" type="text"  name="name" id="name" aria-describedby="helpId" required />
            </div>
            <div class="col">
                <label class="text-dark m-2">Location: </label>
                <input v-model="editable.location" type="text"  name="location" id="location" aria-describedby="helpId" required />
            </div>
            <div class="col">

                <!-- TODO make this a dropdown or something with only the acceptable enum types -->
                <label class="text-dark m-2">Type: </label>
                <input v-model="editable.type" type="text"  name="type" id="type" aria-describedby="helpId" required />
            </div>
            <div class="col">

                <label class="text-dark m-2">Capacity: </label>
                <input v-model="editable.capacity" type="number"  name="capacity" id="capacity" aria-describedby="helpId" required />
            </div>
            <div class="col">
                <label class="text-dark m-2">Start Date: </label>
                <input v-model="editable.startDate" type="date"  name="startDate" id="startDate" aria-describedby="helpId" required />
            </div>
            <div class="col">
                <label class="text-dark m-2">Cover Image: </label>
                <input v-model="editable.coverImg" type="text"  name="coverImg" id="coverImg" aria-describedby="helpId" required />
            </div>
            <div class="col">

                <label class="text-dark m-2">Description: </label>
                <textarea v-model="editable.description" name="description" id="description"  required></textarea>
            </div>



            <button v-if="!event" class="btn btn-success" type="button " @click="">
                Create!
            </button>
            <button class="btn btn-warning" type="button " data-bs-dismiss="modal">Cancel!</button>

        </form>
    </div>
</template>


<script>
import { ref } from "@vue/reactivity"
import { eventsService } from "../services/EventsService"
import Pop from "../utils/Pop"

import { onMounted, watchEffect } from '@vue/runtime-core'
import { Modal } from "bootstrap"
import { useRouter } from "vue-router"
import { logger } from "../utils/Logger"

export default {
    props: { event: { type: Object, required: false } },
    setup() {
        let editable = ref({})
        const router = useRouter()
        return {
            editable,
            async createEvent() {
                try {
                    let eventData = editable.value
                    let newEvent = await eventsService.createEvent(eventData)
                    logger.log('here is the new event', newEvent)
                    Pop.toast('Event listed', 'success')
                    Modal.getOrCreateInstance(document.getElementById('create-event')).hide()
                    
                    router.push({name: "EventDetails", params: {id: newEvent.id}})
                    editable.value = {}
                } catch (error) {
                    Pop.error(error)
                }
            }
        }
    }
}
</script>


<style lang="scss" scoped>
</style>

// towerFE/src/app/components/event-form/event-form.component.ts
import { Component } from '@angular/core';
import { eventType } from "../../app-state";
import { EventFormData } from 'src/app/Interfaces/event-form-data';
import { NgForm, NgModel } from '@angular/forms';
import { AppState } from 'src/app/app-state';
import { EventsService } from 'src/app/Services/events-service.service';
import { TowerEvent } from 'src/app/Interfaces/event';

@Component({
  selector: 'app-event-form',
  templateUrl: './event-form.component.html',
  styleUrls: ['./event-form.component.css']
})
export class EventFormComponent {

  constructor(private eventsService: EventsService, public appState: AppState) {

  }

  originalEventFormData: EventFormData = {
    name: '',
    description: '',
    coverImg: '',
    location: '',
    capacity: 0,
    startDate: new Date(),
    type: eventType.concert 
  }

  eventFormData: EventFormData = {...this.originalEventFormData}

  createEvent(form: NgForm) {
    console.log("form.form.value from createEvent submission:", form.form.value);
    let eventData = form.form.value
    let newEvent: TowerEvent
    this.eventsService.createEvent(eventData).subscribe({
      next: event => {
        newEvent = event
        console.log('here is event from create event subscribe in form:', newEvent);
        this.appState.events.unshift(newEvent)
        console.log('here is appstate events after unshift:', this.appState.events);
        
      }
    })
  }

}

<form class="row" #form="ngForm" (submit)="createEvent(form)" id="event-form">


    <div class="col-1"></div>
    <div class="col-10">
        <div class="row">
            <div class="col-md-5 m-2">
                <label class="text-light m-2">Event Name: </label>
                <input [(ngModel)]="eventFormData.name" type="text" name="name" id="name" aria-describedby="helpId"
                    required />
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Location: </label>
                <input [(ngModel)]="eventFormData.location" type="text" name="location" id="location"
                    aria-describedby="helpId" required />
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Type: </label>
                <select name="type" [(ngModel)]="eventFormData.type" class="form-select" aria-label="type select"
                    required>
                    <option *ngFor="let type of appState.eventTypes" value="{{type}}">{{type}}</option>
                </select>
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Capacity: </label>
                <input min="0" [(ngModel)]="eventFormData.capacity" type="number" name="capacity" id="capacity"
                    aria-describedby="helpId" required />
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Start Date: </label>
                <input [(ngModel)]="eventFormData.startDate" type="date" name="startDate" id="startDate"
                    aria-describedby="helpId" required />
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Cover Image: </label>
                <input [(ngModel)]="eventFormData.coverImg" type="text" name="coverImg" id="coverImg"
                    aria-describedby="helpId" required />
            </div>

            <div class="col-md-5 m-2">
                <label class="text-light m-2">Description: </label>
                <textarea [(ngModel)]="eventFormData.description" name="description" id="description"
                    required></textarea>
            </div>


        </div>
        <div class="row">
            <div class="col-md-5 m-2">
                <button class="btn btn-success m-2" type="button ">Create!</button>
                <button class="btn btn-warning m-2" type="button " data-bs-dismiss="modal">Cancel!</button>
            </div>
        </div>
    </div>
    <div class="col-1"></div>




</form>
