// towerFE/src/app/components/ticket-holder/ticket-holder.component.ts
import { Component, Input } from '@angular/core';
import { Ticket } from 'src/app/Interfaces/ticket';

@Component({
  selector: 'app-ticket-holder',
  templateUrl: './ticket-holder.component.html',
  styleUrls: ['./ticket-holder.component.css']
})
export class TicketHolderComponent {
  @Input() ticket!: Ticket

}

<div>
    <img class="attending-img" [title]="ticket.account.name" [src]="ticket.account.picture" alt="">
</div>

// Tower.client/src/components/TicketHolder.vue
<template>
    <div class="">
<img :title="ticket.account.name" class="attending-img" :src="ticket.account.picture" alt="">


    </div>
</template>


<script>
export default {
    props: { ticket: { type: Object, required: false } },
    setup(){
        return {}
    }
}
</script>


<style lang="scss" scoped>
.attending-img{
    max-width: 30px;
}

</style>
